### ISSUE TITLE
Seems missing a modified Dropzone.js

### ISSUE THREAD

**Issue by shivanraptor** [Dodotree/DropzonePHPchunks#2]
The chunk.js won't work without the modified Dropzone.js, right?

**Comment by Dodotree** [comment]
I don't follow. I've not modified Dropzone.js plugin itself. I just changed settings. You might need to forbid parallel upload too if file size is extremely large for your server.

**Comment by shivanraptor** [comment]
My bad. I was looking into an old version of Dropzone code. Didn't realize that the feature has been implemented in v5.2.0.

Reference: https://gitlab.com/meno/dropzone/wikis/faq#chunked-uploads

**Comment by Dodotree** [comment]
Older version required some combination with resumable.js for chunking.
